### PR TITLE
Make reuse of forcecrc32 code easier for others, reuse libz's crc32()

### PR DESCRIPTION
**Pull request by ehem**
Having the example main() function in a separate file makes reuse distinctly easier.  If one has an existing utility where one wishes to preserve CRCs, not having to rip out an extraneous main() function is helpful.

libz already has a crc32() function which is **much** faster than the example implementation in forcecrc32.c.  Take advantage of the existing code and this makes the code faster.

Replace reverse_bits() with a distinctly faster implementation.  This version might be less obvious how it works, but it does mean some more speed.

### CODE REVIEW

**Comment by ehem** [comment]
I do hereby formally release these enhancements under the terms of the GNU Public License V3 and later versions thereof.  (in case you wanted it formally stated, yes it is GPL3+)

**Comment by nayuki** [comment]
Hello Elliott Mitchell. Thanks for your hard work and earnest contribution. I appreciate how you separated the changes into distinct commits by topic, and the detailed justifications in the commit comments.

Unfortunately I can't accept your code because it doesn't agree with my principles. (I apologize that I haven't published a guide outlining my coding principles.) Specific reasons:

> reverse_bits() optimization

I am aware of the bit-parallel implementation of fixed-width bit reversal (from Hacker's Delight and other sources). I chose to do it the naive way because reverse_bits() isn't a bottleneck in the program, and because the naive way is vastly easier to audit/verify.

> zlib CRC-32

Making use of libraries is not my strong point, nor is writing build/configure/dependency scripts. In this case, I would rather not pull in an enormous library for a ~20-line function.

I did some benchmarking and got 79 MB/s per call of my get_crc32_and_length() function (there are two calls in the main() logic), on a 5-year-old CPU. Honestly for such a niche application that won't be used in bulk, I think it is more than fast enough.

From reading C/C++ code in general, I am pretty offended by the frequent and indiscriminate use of #ifdefs. You might notice that my collection of published C/C++ code tries very hard to avoid this.

> trailing whitespace

I like my style though. It's high-maintenance but logical.

**Comment by nayuki** [comment]
However, I like your idea of splitting out the CRC-forcing logic into its own function, so that it can be called from other code instead of going through the string arguments of main(). I shall implement this in all 3 language versions later this week.

**Comment by nayuki** [comment]
Attention to detail / deep nitpicking - I expect very few people to pass this bar in general:

> ((val >> (1<<s)) & masks[s]) | ((val & masks[s]) << (1<<s));

I'm fairly sure the `|` should be a `+`...

>     reverse_bits(...) { ...
>         for (s = 0; s<sizeof(masks)/sizeof(masks[0]); ++s)
>		      val = ((val >> (1<<s)) & masks[s]) | ((val & masks[s]) << (1<<s));

This style does not match how I space around binary operators, or how I write `s++`.

>     #define _FORCECRC32_H_

I always use `#pragma once` in my published C/C++ header files. #ifdef-guards are just too messy and error-prone.

>     masks[] = {0x55555555, ...

I prefer to wrap each constant in `UINT32_C(...)`.

> (1<<s)

This does not properly defend against undefined behavior if sizeof(int) <= 16. You need to write UINT32_C(1) or (uint32_t)1 before shifting.

**Comment by ehem** [comment]
> I am aware of the bit-parallel implementation of fixed-width bit reversal (from Hacker's Delight and other sources). I chose to do it the naive way because reverse_bits() isn't a bottleneck in the program, and because the naive way is vastly easier to audit/verify.

You're mostly providing example implementations, in such cases they should be _good_ examples.

> Making use of libraries is not my strong point, nor is writing build/configure/dependency scripts. In this case, I would rather not pull in an enormous library for a ~20-line function. I am aware of the table-driven CRC algorithm and opted not to implement it out of simplicity.

I was guessing as much.  Thing is, even though zlib is a ~100KB library, it is already just about everywhere.  Only a few very deeply embedded environments will lack zlib at which point grabbing the functionality from there will be pretty low-cost (notice Python depends on zlib).  I imagine my desktop has at least 10 implementations of crc32() at which point reuse is the way to go.

> From reading C/C++ code in general, I am pretty offended by the frequent and indiscriminate use of #ifdefs. You might notice that my collection of published C/C++ code tries very hard to avoid this.

It was needed to keep the option of using the internal crc32 versus the zlib crc32.  The commit after removed two of those in the hope of making the comparison between zlib's crc32() function and what your function was doing more obvious.  Could also simply remove the internal implementation and exclusively use zlib's implementation.

 .

> However, I like your idea of splitting out the CRC-forcing logic into its own function, so that it can be called from other code instead of going through the string arguments of main(). I shall implement this in all 3 language versions later this week.

That was my primary goal.  I'm doing a bit of software where being able to rig things to match an existing CRC32 _may_ be of value.

 .

> > ((val >> (1<<s)) & masks[s]) | ((val & masks[s]) << (1<<s));
>
> I'm fairly sure the | should be a +...

That would work too, but I prefer bitwise-or for this situation, needs fewer transistors and matches what is being done better.  Bitwise exclusive-or is another operator which would work.  _All_ of these work since the bits set in each half will be disjoint.

> This style does not match how I space around binary operators, or how I write `s++`.

Rarely a big deal nowadays, but pre-increment/decrement is preferred since it doesn't create a temporary.  Most compilers will optimize that out nowadays, but those who have been around a while will still prefer the pre format.

> I always use `#pragma once` in my published C/C++ header files. #ifdef-guards are just too messy and error-prone.

I thought you were being careful to _strictly_ stick to what standards allow.  #ifdef-guards are standard C, `#pragma once` is _highly_ compiler-dependent.  They're also reliable enough for pretty well all system headers.

> > (1<<s)
> 
> This does not properly defend against undefined behavior if sizeof(int) <= 16. You need to write UINT32_C(1) or (uint32_t)1 before shifting.

I think you mean `sizeof(int) <= 2` (hmm, you've got a computer with 128-bit wide general-purpose registers? impressive; while I think you meant 16 bits).  Perhaps in the general case, but certainly not here.  As long as `sizeof(int) >= 0.75` (1.5 nybbles, 6 bits) the code won't hit that limit, the maximum value of that expression ever gets is 16 (s=4).

**Comment by ehem** [comment]
Grr, two close together buttons which have rather different effects and no confirmation on either.

**Comment by nayuki** [comment]
Thanks for the response. Wow I made some basic mistakes. I really should not have tried to read/write code while on vacation.

> I'm fairly sure the `|` should be a `+`

I got mixed up between reverseBits() and hammingWeight(), because the algorithms look so similar. My bad.

> I think you mean sizeof(int) <= 2

Two mistakes I made there: I did mean 16 bits, and somehow I thought `s` went 1, 2, 4, 8, 16 instead of 0, 1, 2, 3 (i.e. `1 << (1 << s)`).

**Comment by nayuki** [comment]
Superseded by my changes in https://github.com/nayuki/Nayuki-web-published-code/commit/4e524fd20935ddb0c8b4e7f01f6a776d91051e07 .

This commit factors out the CRC-32 patching logic into a separate function that can be called from other code, without going through string representations or even exec().

**Pull request closed without merging**
